name: CI

on: [push]

defaults:
  run:
    shell: bash
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install boost
        run: |
          BOOST_VERSION=1_70_0
          BOOST_ARCHIVE=boost_${BOOST_VERSION}.tar.gz
          BOOST_DIRECTORY=boost_$BOOST_VERSION
          BOOST_DOWNLOAD_URL=https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION//_/.}
          wget ${BOOST_DOWNLOAD_URL}/${BOOST_ARCHIVE}
          tar xzf ${BOOST_ARCHIVE}
          cd ${BOOST_DIRECTORY}
          ./bootstrap.sh --prefix=$HOME/boost cxxstd=11 --without-icu --with-toolset=gcc --with-libraries=filesystem,program_options,serialization,system,log,iostreams
          ./b2 -j 3 cxxflags="-std=c++11 -fPIC" toolset=gcc variant=release install
          ls $HOME/boost/lib/cmake/Boost-1.70.0

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Configure CMake
        run: >
          cmake -S $GITHUB_WORKSPACE/SolutionBoostDll -B $GITHUB_WORKSPACE/build-linux
          -DLIBRARY_TYPE=STATIC
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install-static
          -DBoost_DIR=$HOME/boost/lib/cmake/Boost-1.70.0
          -G "Unix Makefiles"

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build-linux

      - name: Install
        run: cmake --install $GITHUB_WORKSPACE/build-linux

      - name: Run
        run: |
          cd $GITHUB_WORKSPACE/install-static/bin
          ./dlopen_singleton
          cat sample.log

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - name: Install boost
        run: |
          BOOST_VERSION=1_70_0
          BOOST_ARCHIVE=boost_${BOOST_VERSION}.tar.gz
          BOOST_DIRECTORY=boost_$BOOST_VERSION
          BOOST_DOWNLOAD_URL=https://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION//_/.}
          wget ${BOOST_DOWNLOAD_URL}/${BOOST_ARCHIVE}
          tar xzf ${BOOST_ARCHIVE}
          cd ${BOOST_DIRECTORY}
          ./bootstrap.sh --prefix=$HOME/boost cxxstd=11 --without-icu --with-toolset=clang --with-libraries=filesystem,program_options,serialization,system,log,iostreams
          ./b2 -j 3 cxxflags="-std=c++11 -fPIC" toolset=clang variant=release install

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Configure CMake
        run: >
          cmake -S $GITHUB_WORKSPACE/SolutionBoostDll -B $GITHUB_WORKSPACE/build-macos
          -DLIBRARY_TYPE=STATIC
          -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install-static
          -DBoost_DIR=$HOME/boost/lib/cmake/Boost-1.70.0
          -G "Unix Makefiles"

      - name: Build
        run: cmake --build $GITHUB_WORKSPACE/build-macos

      - name: Install
        run: cmake --install $GITHUB_WORKSPACE/build-macos

      - name: Run
        run: |
          cd $GITHUB_WORKSPACE/install-static/bin
          ./dlopen_singleton
          cat sample.log

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Install boost
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          choco install wget --no-progress
          wget https://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.zip
          7z x boost_1_70_0.zip
          cd boost_1_70_0
          call bootstrap.bat msvc
          b2 -j 2 -sNO_BZIP2=1 install --prefix=%USERPROFILE%\boost-static --disable-icu --layout=system architecture=x86 address-model=64 variant=debug link=static runtime-link=static stage

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S %GITHUB_WORKSPACE%\SolutionBoostDll -B %GITHUB_WORKSPACE%\build-windows ^
          -DLIBRARY_TYPE=STATIC ^
          -DCMAKE_BUILD_TYPE=Debug ^
          -DCMAKE_INSTALL_PREFIX=%GITHUB_WORKSPACE%\install-static ^
          -DMSVC_STATIC_RUNTIME_LIBRARY=ON ^
          -DBoost_DIR=%USERPROFILE%\boost-static\lib\cmake\Boost-1.70.0 ^
          -G "NMake Makefiles"

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake --build %GITHUB_WORKSPACE%\build-windows

      - name: Build
        shell: cmd
        run:
          cmake --install %GITHUB_WORKSPACE%\build-windows

      - name: Run
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%\install-static\bin
          dlopen_singleton
